### PR TITLE
Fix Callback/Promise never resolve

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by SamVerschueren** [comment]
What happens if the connection already is open and you subscribe afterwards? Or should we do it like this:
1. Is connection open?
2. If already open, start seeding
3. If not yet open, subscribe to the event

**Comment by SamVerschueren** [comment]
Tests are failing as well. Can you look into that?

**Comment by ghost** [comment]
The following code checks the state of the db connection, if it's open, it starts seeding. Otherwise, it subscribes to the event if it's opening. The `ready()` function merely encapsulates the db drop and seeding logic which already exists.

If it's closed, or closing, it sends an error to the `done()` function.

```
switch(mongoose.connection.readyState) {
    case 0: //disconnected
        done("db not open");
        break;
    case 1: //connected
        ready();
        break;
    case 2: //connecting
        mongoose.connection.on('connected', function() {
            ready();
        });
        break;
    case 3: //disconnecting
        done("db disconnecting");
        break;
    default: //any other state
        done("unknown db state");
        break;
}
```

However, the tests continue to fail unless I wrap the `Callback Database` & `Promises Database` Connection Error tests with a 

```
mongoose.connection.on('disconnected', function() {
    connect(done);
});
```

which result in either `done()` being called multiple times in the `Callback` test or timing out in the `Promises` test.

I'm not 100% sure how to proceed from here, but here is the [commit](https://github.com/fedoranimus/mongoose-seeder/commit/cf9bc28076e87c19dd0ac7be7f6317399b0b0c69) if it helps.

**Comment by SamVerschueren** [comment]
I'm still looking for a maintainer as I can't find the time to work on this anymore. Feel free to respond. For now, I'm going to close this PR. Sorry for the inconvenience!

**Pull request closed without merging**
